// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDntHcQuC2ByYTQmrxyn1r6WKWq0iqoWSo',
    appId: '1:650795143989:web:16b5e68baecb063ca0327c',
    messagingSenderId: '650795143989',
    projectId: 'hello-e528d',
    authDomain: 'hello-e528d.firebaseapp.com',
    storageBucket: 'hello-e528d.firebasestorage.app',
    measurementId: 'G-7PC9YRRMD0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbeT-55rEqpEnu9ttoUerL_hkrLnc9Dns',
    appId: '1:650795143989:android:8d135fc01d31e074a0327c',
    messagingSenderId: '650795143989',
    projectId: 'hello-e528d',
    storageBucket: 'hello-e528d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjK1sLXI1iWlQN3QP0cwVSAJ4OpZiijb0',
    appId: '1:650795143989:ios:61a9f8fc7eb4f75da0327c',
    messagingSenderId: '650795143989',
    projectId: 'hello-e528d',
    storageBucket: 'hello-e528d.firebasestorage.app',
    iosBundleId: 'com.example.testproject2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjK1sLXI1iWlQN3QP0cwVSAJ4OpZiijb0',
    appId: '1:650795143989:ios:61a9f8fc7eb4f75da0327c',
    messagingSenderId: '650795143989',
    projectId: 'hello-e528d',
    storageBucket: 'hello-e528d.firebasestorage.app',
    iosBundleId: 'com.example.testproject2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDntHcQuC2ByYTQmrxyn1r6WKWq0iqoWSo',
    appId: '1:650795143989:web:ab1a20ed6f3ab368a0327c',
    messagingSenderId: '650795143989',
    projectId: 'hello-e528d',
    authDomain: 'hello-e528d.firebaseapp.com',
    storageBucket: 'hello-e528d.firebasestorage.app',
    measurementId: 'G-46F8P0RRHZ',
  );

}